<?PHP
$manifest = array(
    'name' => 'ZuckerReports2 - DemoPack',
    'description' => 'ZuckerReports2 - DemoPack',
    'author' => 'ZuckerFriends GmbH',
    'published_date' => '2012/06/14',
    'version' => '2.0',
    'type' => 'module',
    'icon' => '',
	'is_uninstallable' => 'true',
);

$installdefs = array(
	'id'=> 'ZuckerReports2_DemoPack',
	'copy' => array(
			array('from'=> '<basepath>/Activity.jrxml',
		  	'to'=> 'cache/upload/Activity.jrxml',
			),
			array('from'=> '<basepath>/ClosedOpportunitiesSubreport.jrxml',
		  	'to'=> 'cache/upload/ClosedOpportunitiesSubreport.jrxml',
			),
			array('from'=> '<basepath>/LostOpportunitiesSubreport.jrxml',
		  	'to'=> 'cache/upload/LostOpportunitiesSubreport.jrxml',
			),
			array('from'=> '<basepath>/NewOpportunitiesSubreport.jrxml',
		  	'to'=> 'cache/upload/NewOpportunitiesSubreport.jrxml',
			),
			array('from'=> '<basepath>/ClosedDeals.jrxml',
		  	'to'=> 'cache/upload/ClosedDeals.jrxml',
			),
			array('from'=> '<basepath>/MeetingPrintout.jrxml',
		  	'to'=> 'cache/upload/MeetingPrintout.jrxml',
			),
			array('from'=> '<basepath>/MeetingPrintout_Contacts.jrxml',
		  	'to'=> 'cache/upload/MeetingPrintout_Contacts.jrxml',
			),
			array('from'=> '<basepath>/MeetingPrintout_Users.jrxml',
		  	'to'=> 'cache/upload/MeetingPrintout_Users.jrxml',
			),
			array('from'=> '<basepath>/logo.gif',
		  	'to'=> 'cache/upload/logo.gif',
			),
			array('from'=> '<basepath>/Opportunities.jrxml',
		  	'to'=> 'cache/upload/Opportunities.jrxml',
			),
			array('from'=> '<basepath>/OpportunitiesByIndustry.jrxml',
		  	'to'=> 'cache/upload/OpportunitiesByIndustry.jrxml',
			),
			array('from'=> '<basepath>/OpportunityHistoryDetail.jrxml',
		  	'to'=> 'cache/upload/OpportunityHistoryDetail.jrxml',
			),
			array('from'=> '<basepath>/PipelineBySalesStageChart.jrxml',
		  	'to'=> 'cache/upload/PipelineBySalesStageChart.jrxml',
			),
	),
);
?>
