<?PHP
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

/**
 * THIS CLASS IS GENERATED BY MODULE BUILDER
 * PLEASE DO NOT CHANGE THIS CLASS
 * PLACE ANY CUSTOMIZATIONS IN a0423_Agreements
 */


class a0423_Agreements_sugar extends Basic {
	var $new_schema = true;
	var $module_dir = 'a0423_Agreements';
	var $object_name = 'a0423_Agreements';
	var $table_name = 'a0423_agreements';
	var $importable = true;
	var $disable_row_level_security = true ; // to ensure that modules created and deployed under CE will continue to function under team security if the instance is upgraded to PRO
		var $id;
		var $name;
		var $date_entered;
		var $date_modified;
		var $modified_user_id;
		var $modified_by_name;
		var $created_by;
		var $created_by_name;
		var $description;
		var $deleted;
		var $created_by_link;
		var $modified_user_link;
		var $assigned_user_id;
		var $assigned_user_name;
		var $assigned_user_link;
		var $proposal_approved_date;
		var $agreement_number;
		var $agreement_date;
		var $agreemment_budget;
		var $po_number;
		var $report_cycle_type;
		var $number_of_periods;
		var $number_of_participants;
		var $program_start_date;
		var $program_end_date;
		var $report_cycle;
		var $number_of_payments;
		var $budgeted_award_amount;
		var $budgeted_instr_exp;
		var $budgeted_materials_exp;
		var $budgeted_tranportation_exp;
		var $budgeted_activity_exp;
		var $budgeted_administrative_exp;
		var $budgeted_food_exp;
		var $budgeted_accommodation_exp;
		var $total_afterschool_instr_hrs;
		var $afterschool_instr_hrs_per_week;
		var $number_of_afterschool_weeks;
		var $total_intens_session_instr_hrs;
		var $number_of_intens_sessions;
		var $intens_sessions_hrs_per_week;
		var $number_of_intens_session_weeks;
		var $total_instr_hrs;
		var $sub_agreement_status;
		var $fiscal_year;
		function a0423_Agreements_sugar(){	
		parent::Basic();
	}
	
	function bean_implements($interface){
		switch($interface){
			case 'ACL': return true;
		}
		return false;
}
		
}
?>