<?php
/*********************************************************************************
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 * 
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 * details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 * 
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 * 
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 * 
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo. If the display of the logo is not reasonably feasible for
 * technical reasons, the Appropriate Legal Notices must display the words
 * "Powered by SugarCRM".
 ********************************************************************************/

$relationships = array (
  'a0423_agreements_modified_user' => 
  array (
    'id' => '1e9103f6-f223-0483-d20d-520a8c1de2e2',
    'relationship_name' => 'a0423_agreements_modified_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'a0423_Agreements',
    'rhs_table' => 'a0423_agreements',
    'rhs_key' => 'modified_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'a0423_agreements_created_by' => 
  array (
    'id' => '1edfc656-84d3-3d0a-cd47-520a8c494b42',
    'relationship_name' => 'a0423_agreements_created_by',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'a0423_Agreements',
    'rhs_table' => 'a0423_agreements',
    'rhs_key' => 'created_by',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'a0423_agreements_assigned_user' => 
  array (
    'id' => '1f166513-b520-1902-3a1f-520a8c8dbd0c',
    'relationship_name' => 'a0423_agreements_assigned_user',
    'lhs_module' => 'Users',
    'lhs_table' => 'users',
    'lhs_key' => 'id',
    'rhs_module' => 'a0423_Agreements',
    'rhs_table' => 'a0423_agreements',
    'rhs_key' => 'assigned_user_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
  ),
  'a0423_agreements_activities_1_notes' => 
  array (
    'id' => '5e634d54-5a9e-4aed-30a5-520a8c3c6622',
    'relationship_name' => 'a0423_agreements_activities_1_notes',
    'lhs_module' => 'a0423_Agreements',
    'lhs_table' => 'a0423_agreements',
    'lhs_key' => 'id',
    'rhs_module' => 'Notes',
    'rhs_table' => 'notes',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'a0423_Agreements',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'contacts_a0423_agreements_1' => 
  array (
    'id' => '63bfb905-a714-6195-3fc0-520a8c86af20',
    'relationship_name' => 'contacts_a0423_agreements_1',
    'lhs_module' => 'Contacts',
    'lhs_table' => 'contacts',
    'lhs_key' => 'id',
    'rhs_module' => 'a0423_Agreements',
    'rhs_table' => 'a0423_agreements',
    'rhs_key' => 'id',
    'join_table' => 'contacts_a0423_agreements_1_c',
    'join_key_lhs' => 'contacts_a0423_agreements_1contacts_ida',
    'join_key_rhs' => 'contacts_a0423_agreements_1a0423_agreements_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'a0423_agreements_opportunities_1' => 
  array (
    'id' => '6418db3c-1f3d-7053-5569-520a8c2d3bc6',
    'relationship_name' => 'a0423_agreements_opportunities_1',
    'lhs_module' => 'a0423_Agreements',
    'lhs_table' => 'a0423_agreements',
    'lhs_key' => 'id',
    'rhs_module' => 'Opportunities',
    'rhs_table' => 'opportunities',
    'rhs_key' => 'id',
    'join_table' => 'a0423_agreements_opportunities_1_c',
    'join_key_lhs' => 'a0423_agreements_opportunities_1a0423_agreements_ida',
    'join_key_rhs' => 'a0423_agreements_opportunities_1opportunities_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'accounts_a0423_agreements_1' => 
  array (
    'id' => '648d6453-28ad-e73e-6914-520a8c856aec',
    'relationship_name' => 'accounts_a0423_agreements_1',
    'lhs_module' => 'Accounts',
    'lhs_table' => 'accounts',
    'lhs_key' => 'id',
    'rhs_module' => 'a0423_Agreements',
    'rhs_table' => 'a0423_agreements',
    'rhs_key' => 'id',
    'join_table' => 'accounts_a0423_agreements_1_c',
    'join_key_lhs' => 'accounts_a0423_agreements_1accounts_ida',
    'join_key_rhs' => 'accounts_a0423_agreements_1a0423_agreements_idb',
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => NULL,
    'relationship_role_column_value' => NULL,
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => 'default',
    'lhs_subpanel' => NULL,
    'from_studio' => true,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
  ),
  'a0423_agreements_activities_1_tasks' => 
  array (
    'id' => '651a87a6-5735-6f30-faa7-520a8c37c3f0',
    'relationship_name' => 'a0423_agreements_activities_1_tasks',
    'lhs_module' => 'a0423_Agreements',
    'lhs_table' => 'a0423_agreements',
    'lhs_key' => 'id',
    'rhs_module' => 'Tasks',
    'rhs_table' => 'tasks',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'a0423_Agreements',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'a0423_agreements_activities_1_calls' => 
  array (
    'id' => '655487d8-6303-b159-356e-520a8c7fa7a5',
    'relationship_name' => 'a0423_agreements_activities_1_calls',
    'lhs_module' => 'a0423_Agreements',
    'lhs_table' => 'a0423_agreements',
    'lhs_key' => 'id',
    'rhs_module' => 'Calls',
    'rhs_table' => 'calls',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'a0423_Agreements',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'a0423_agreements_activities_1_meetings' => 
  array (
    'id' => '658fd5f1-6d6b-2144-d214-520a8c7f6eea',
    'relationship_name' => 'a0423_agreements_activities_1_meetings',
    'lhs_module' => 'a0423_Agreements',
    'lhs_table' => 'a0423_agreements',
    'lhs_key' => 'id',
    'rhs_module' => 'Meetings',
    'rhs_table' => 'meetings',
    'rhs_key' => 'parent_id',
    'join_table' => NULL,
    'join_key_lhs' => NULL,
    'join_key_rhs' => NULL,
    'relationship_type' => 'one-to-many',
    'relationship_role_column' => 'parent_type',
    'relationship_role_column_value' => 'a0423_Agreements',
    'reverse' => '0',
    'deleted' => '0',
    'readonly' => true,
    'rhs_subpanel' => NULL,
    'lhs_subpanel' => NULL,
    'is_custom' => true,
    'relationship_only' => false,
    'for_activities' => false,
    'from_studio' => true,
  ),
  'a0423_agreements_contacts_1' => 
  array (
    'rhs_label' => 'Contacts_Agr',
    'lhs_label' => 'Agreements',
    'rhs_subpanel' => 'default',
    'lhs_module' => 'a0423_Agreements',
    'rhs_module' => 'Contacts',
    'relationship_type' => 'one-to-many',
    'readonly' => true,
    'deleted' => false,
    'relationship_only' => false,
    'for_activities' => false,
    'is_custom' => false,
    'from_studio' => true,
    'relationship_name' => 'a0423_agreements_contacts_1',
  ),
);